<?php

class Uchinka_CustomGrid_Block_Adminhtml_Customgrid_Grid extends Mage_Adminhtml_Block_Widget_Grid
{

    protected $_filterVisibility = false;

    public function __construct()
    {
        parent::__construct();

        $this->setDefaultSort('sort_order');
        $this->setId('customgrid_grid');
        $this->setDefaultDir('asc');
        $this->setSortable(false);
        $this->setDefaultLimit(20);
    }



    protected function _prepareCollection()
    {
        $collection = new Varien_Data_Collection();

        $this->setCollection($collection);
        return parent::_prepareCollection();
    }

    public function getPagerVisibility() {
        return false;
    }


    protected function _prepareColumns()
    {
        $this->addColumn('column_id',
            array(
                'header'=> $this->__('ID'),
                'width' => '30',
                'index' => 'column_id',
                'type'  => 'number'
            )
        );
        $this->addColumn('attribute_code',
            array(
                'header'=> $this->__('Attribute'),
                'index' => 'attribute_code',
            )
        );

        $this->addColumn('label',
            array(
                'header'     => 'Label',
                'renderer'   => 'customgrid/adminhtml_widget_grid_column_renderer_label',
            )
        );

        $this->addColumn('sort_order',
            array(
                'header'=> 'Sort order',
                'index' => 'sort_order',
                'header_css_class'    => 'a-right',
                'type'  => 'number',
            )
        );

        $this->addColumn('width',
            array(
                'header'=> 'Width',
                'header_css_class'    => 'a-right',
                'renderer'   => 'customgrid/adminhtml_widget_grid_column_renderer_width',
            )
        );

        $this->addColumn('status', array(
            'header'    => 'Enable',
            'type'      => 'checkbox',
            'header_css_class'    => 'a-center',
            'value'     => '1',
            'index'     => 'status'
        ));

        $this->addColumn('action',
            array(
                'header'    => 'Action',
                'header_css_class'    => 'a-right p-right',
                'renderer'  => 'customgrid/adminhtml_widget_grid_column_renderer_action',
                'filter'    => false,
                'align'     => 'right',
            ));



        return parent::_prepareColumns(); // TODO: Change the autogenerated stub
    }

    public function getEmptyText() {
        return '';
    }

    protected function _getUserId()
    {
        return Mage::getSingleton('admin/session')->getUser()->getId();
    }

    public function getRowUrl($item)
    {
        return '';
    }
}