<?php
?>
<?php echo $this->getChildHtml('global_messages') ?>
<div class="u-overlay-loading">
    <div class="u-loading-gif" style="background: url(<?php echo $this->getSkinUrl('images/uchinka/loading.gif'); ?>);"></div>
</div>
<div class="content-header">
    <table cellspacing="0">
        <tr>
            <td style="<?php echo $this->getHeaderWidth() ?>"><?php echo $this->getHeaderHtml() ?></td>
            <td class="form-buttons"><?php echo $this->getButtonsHtml() ?></td>
        </tr>
    </table>
</div>
<div>
    <div class="u-form-add-new-column">
        <form action="<?php echo $this->getUrl('adminhtml/customgrid_index/new') ?>" id="u-add-column-form">
            <table class="form-list">
                <tr>
                    <td>
                        <label for="u-select-attribute-code">Select column (*)</label>
                        <br>
                        <select id="u-select-attribute-code" name="attribute_id" required>
                        </select>
                    </td>
                    <td>
                        <label for="u-input-attribute-label">Custom label</label>
                        <br>
                        <input id="u-input-attribute-label" type="text" name="label">
                    </td>
                    <td>
                        <label for="u-input-attribute-width">Width</label>
                        <br>
                        <input id="u-input-attribute-width" type="number" name="width" value="50"> (px)
                    </td>
                </tr>
                <tr>
                    <td>
                        <?php echo $this->getBlockHtml('formkey')?>
                        <button type="submit" class="scalable add" style=""><span><span><span>Add new</span></span></span></button>
                        <button id="u-btn-cancel" class="scalable" style=""><span><span><span>Cancel</span></span></span></button>
                    </td>
                </tr>
            </table>
        </form>
    </div>
    <?php echo $this->getGridHtml() ?>
</div>
<script>
    let currentAttributeIds = [<?php echo implode(',', $this->getChild('grid')->getCurrentAttributeIds()) ?>];

    let listAttribute = <?php echo json_encode($this->getAllAttribute()) ?>
</script>