<script>
    let url = '<?php echo $this->getUrl('adminhtml/catalog_product'); ?>';

    let isUpdated = false;

    jQuery(function ($) {
        $('.custom-grid-btn.btn-delete').click(function (e) {
            if (confirm('Do you want to delete row id ' + $(e.target).attr('data-id'))) {
                toggleImgLoading();
                $.get($(e.target).attr('data-url')).done(function (e) {
                    console.log(e);
                }).always(function () {
                    toggleImgLoading(false);
                });
            }
        });

        $('.custom-grid-btn.edit').click(function (e) {

        });

        $('#u-add-column-form').submit(function (e) {
            e.preventDefault();
            let form = $(e.target).serializeArray();
            let attributeId = +form[0].value;
            let attributeLabel = form[1].value;
            let attributeWidth = +form[2].value;
            let isExisted = currentAttributeIds.find(function (e) {
                return +e.attribute_id === attributeId
            })
            if (isExisted !== undefined) {
                return false;
            }
            let selectedAttr = listAttribute.find(function (e) {
                return +e.attribute_id === attributeId
            });
            if (selectedAttr) {
                attributeLabel = attributeLabel === '' ? selectedAttr.frontend_label : attributeLabel;
                let html = `<tr id="column-1-65" title="" class="">
                            <td class=" a-right ">NULL</td>
                            <td class=" ">
                                ${selectedAttr.attribute_code} </td>
                            <td class=" ">
                                <span class="u-show-first-group"> ${attributeLabel}</span>
                                <input type="text" class="u-hidden-first-group" value="${attributeLabel}"> </td>
                            <td class=" a-right ">
                                0 </td>
                            <td class=" ">
                                <span class="u-show-first-group">${attributeWidth}px</span>
                                <input type="text" class="u-hidden-first-group" value="50"> </td>
                            <td class=" ">
                                <input type="checkbox" name="" value="14" class="checkbox" checked="checked"> </td>
                            <td class=" last">
                                <span class="custom-grid-btn btn-edit" data-id="14" style="background-image: url(http://magento1.local/skin/adminhtml/default/default/images/icon_edit_address.gif);"></span><span class="custom-grid-btn btn-delete" data-id="14" data-url="http://magento1.local/index.php/admin/customgrid_index/delete/id/14/key/b3caccbae748f866a8c04f89a9eb926d/" style="background-image: url(http://magento1.local/skin/adminhtml/default/default/images/icon_btn_delete.gif);"></span> </td>
                        </tr>`
                $('#customgrid_grid_table > tbody').append(html);
                let newColumn = {
                    attribute_id: attributeId,
                    column_id: null,
                    label: attributeLabel === '' ? '' : attributeLabel,
                    sort_order: '0',
                    status: '1',
                    width: '50'
                };
                currentAttributeIds.push(newColumn);
                doOrderColumnEven();
            }
        });

        $('#u-btn-cancel').click(function () {
            jQuery('.u-form-add-new-column').hide();
            jQuery('#u-btn-add-column').show();
        });
        $('#customgrid_grid_table > tbody').sortable({
            axis: 'y',
            cursor: 'move',
            update: function (e) {
                console.log(e)
                $('#u-btn-save-order').show();
                doOrderColumnEven();
                activeSaveBtn();
            }
        });


    })

    let reLoadSelectAttributeCode = function () {
        let select = jQuery('#u-select-attribute-code');
        select.html('');
        let options = '';
        filterAttribute(listAttribute, currentAttributeIds).forEach(e => {
            options += `<option value="${e.attribute_id}">${Boolean(e.frontend_label) ? e.frontend_label : e.attribute_code}</option>`
        });
        select.html(options);
    };

    let filterAttribute = function (attr, curr) {
        return attr.filter(e => {
            return !curr.some(function (ee) {
                return +ee.attribute_id === +e.attribute_id;
            })
        })
    }

    let showCreateColumn = function () {
        jQuery('.u-form-add-new-column').show();
        jQuery('#u-btn-add-column').hide();
        reLoadSelectAttributeCode();
    }

    let toggleImgLoading = function (value = true) {
        if (value) {
            jQuery('.u-overlay-loading').show();
        } else {
            jQuery('.u-overlay-loading').hide();
        }
    }

    let activeSaveBtn = function (status = true) {
        if (!isUpdated && status) {
            jQuery('#u-btn-save-column').removeClass('disabled');
            isUpdated = true
        }
        if (!status) {
            jQuery('#u-btn-save-column').addClass('disabled');
            isUpdated = false
        }
    };


    let doOrderColumnEven = function () {
        let id = null;
        let newArray = [];
        jQuery('#customgrid_grid_table tbody tr').each((i, e) => {
            if (i % 2 === 0) {
                e.className = 'even ui-sortable-handle';
            } else {
                e.className = 'ui-sortable-handle';
            }


            jQuery(jQuery(e).find('td')[3]).text(i + 1);
            id = +jQuery(e).find('input[name="hidden_attribute_id"]').val();
            let currentObject = currentAttributeIds.find(function (ee) {
                return +ee.attribute_id === id
            })
            if (currentObject) {
                newArray.push(currentObject);
            }
        })
        currentAttributeIds = Object.assign([], newArray);
    };

    let closePopup = function () {
        if (isUpdated) {
            if (confirm('Your setting is not saved, do you want close popup?')) {
                parent.postMessage('close_popup', '*')
            }
        } else {
            parent.postMessage('close_popup', '*')
        }
    }

</script>