<script>
    let url = '<?php echo $this->getUrl('adminhtml/catalog_product'); ?>';

    let isUpdated = false;

    jQuery(function($) {
        $('.custom-grid-btn.btn-delete').click(function(e) {
            if (confirm('Do you want to delete row id '+ $(e.target).attr('data-id'))) {
                toggleImgLoading();
                $.get($(e.target).attr('data-url')).done(function (e) {
                    console.log(e);
                }).always(function() {
                    toggleImgLoading(false);
                });
            }
        });

        $('.custom-grid-btn.edit').click(function (e) {

        });

        $('#u-add-column-form').submit(function(e) {
            e.preventDefault();
            let form = $(e.target);
            toggleImgLoading();
            $.post(form.attr('action'), form.serialize()).done(function (e) {
                console.log(e);
            }).always(function () {
                toggleImgLoading(false);
            });
        })

        $('#u-btn-cancel').click(function() {
            jQuery('.u-form-add-new-column').hide();
            jQuery('#u-btn-add-column').show();
        })
        $('#customgrid_grid_table > tbody').sortable({
            axis: 'y',
            cursor: 'move',
            update: function (e) {
                $('#u-btn-save-order').show();
            }
        })

    })

    let reLoadSelectAttributeCode = function () {
        let select = jQuery('#u-select-attribute-code');
        select.html('');
        let options = '';
        filterAttribute(listAttribute, currentAttributeIds).forEach(e => {
            options += `<option value="${e.attribute_id}">${Boolean(e.frontend_label) ? e.frontend_label : e.attribute_code}</option>`
        });
        select.html(options);
    };

    let filterAttribute = function (attr, curr) {
        return attr.filter(e => {
            return !curr.includes(+e.attribute_id)
        })
    }

    let showCreateColumn = function () {
        jQuery('.u-form-add-new-column').show();
        jQuery('#u-btn-add-column').hide();
        reLoadSelectAttributeCode();
    }

    let toggleImgLoading = function (value = true) {
        if (value) {
            jQuery('.u-overlay-loading').show();
        } else {
            jQuery('.u-overlay-loading').hide();
        }
    }



    let closePopup = function () {
        parent.postMessage('Hello', '*')
    }

</script>