<?php

class Uchinka_SaleOff_Block_SaleOff extends Mage_Core_Block_Template
{
    protected $_template = 'saleoff.phtml';

    protected $image_helper;

    public function _construct()
    {
        $this->image_helper = Mage::helper('catalog/image');
        parent::_construct(); // TODO: Change the autogenerated stub
    }

    protected function _beforeToHtml()
    {
        $products = $this->indexSaleOff();
        $products['list'] = array_filter($products['list'], function($item) {
            return true; //!empty($item->getData('slide_img'));
        });
        $this->assign('products', $products);
        return parent::_beforeToHtml();
    }

    public function indexSaleOff()
    {
        $category = Mage::getModel('catalog/category');
        /* TODO - make a config to set category id in admin */
        $categoryIdConfig = Mage::getStoreConfig('catalogsaleoff/general/category_id');
        $countConfig = Mage::getStoreConfig('catalogsaleoff/general/product_count');
        $transitionEffectConfig = Mage::getStoreConfig('catalogsaleoff/slider/transition_effect');
        $delayConfig = Mage::getStoreConfig('catalogsaleoff/slider/delay');
        $category = $category->load($categoryIdConfig);
        $products = $category->getProductCollection();
        $products->addAttributeToSelect('*')->setPageSize($countConfig);
        return [
            'list' => $products->getItems(),
            'config' => [
                'fx' => $transitionEffectConfig,
                'delay' => $delayConfig,
            ]
        ];
    }
}